disabled_rules:
  - nesting
  - large_tuple
  - file_length

excluded:
  - Pods
  - Carthage
  - SourcePackages
  - Generated
  - R.generated.swift

line_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 1
